onerror {resume}
quietly WaveActivateNextPane {} 0
add wave -noupdate /integeration/clk
add wave -noupdate /integeration/rst
add wave -noupdate /integeration/en
add wave -noupdate /integeration/E/ExtendCCR/in_signal
add wave -noupdate /integeration/E/ExtendCCR/out_signal
add wave -noupdate /integeration/M/clk
add wave -noupdate /integeration/M/Rst
add wave -noupdate /integeration/M/Mem_Read
add wave -noupdate /integeration/M/Mem_Write
add wave -noupdate /integeration/M/S_P
add wave -noupdate /integeration/M/Push
add wave -noupdate /integeration/M/Pop
add wave -noupdate /integeration/M/call
add wave -noupdate /integeration/M/RTI
add wave -noupdate /integeration/M/INT
add wave -noupdate /integeration/M/Write_data
add wave -noupdate /integeration/M/address_from_ALU
add wave -noupdate /integeration/M/data_from_call
add wave -noupdate /integeration/M/PC_for_int
add wave -noupdate /integeration/M/read_data
add wave -noupdate /integeration/M/address
add wave -noupdate /integeration/M/address_from_SP
add wave -noupdate /integeration/M/Add_sub_Result
add wave -noupdate /integeration/M/Data_concatenated
add wave -noupdate /integeration/M/data_to_write
add wave -noupdate /integeration/M/Write_data32
add wave -noupdate /integeration/M/data_from_call32
add wave -noupdate /integeration/M/Push_or_Pop
add wave -noupdate /integeration/M/Push_or_NotPop
add wave -noupdate /integeration/M/INT_or_RTI
add wave -noupdate /integeration/M/one_or_two
add wave -noupdate /integeration/M/Push_or_Pop_extend
add wave -noupdate /integeration/M/add
add wave -noupdate /integeration/M/POP_Or_RTI
add wave -noupdate /integeration/IN_Port
add wave -noupdate /integeration/OUT_Port
add wave -noupdate /integeration/Interrupt
add wave -noupdate /integeration/Output_from_FD_For_call
add wave -noupdate /integeration/Output_From_FD_Instruction
add wave -noupdate /integeration/Output_from_FD_Inport
add wave -noupdate /integeration/Output_From_FD_INT
add wave -noupdate /integeration/output_from_DE_For_call
add wave -noupdate /integeration/output_from_DE_RTI
add wave -noupdate /integeration/output_from_DE_RET
add wave -noupdate /integeration/output_from_DE_WB_MemtoReg
add wave -noupdate /integeration/output_from_DE_Call
add wave -noupdate /integeration/output_from_DE_Push
add wave -noupdate /integeration/output_from_DE_Pop
add wave -noupdate /integeration/output_from_DE_INT
add wave -noupdate /integeration/output_from_DE_WB_RegToReg
add wave -noupdate /integeration/output_from_DE_memRead
add wave -noupdate /integeration/output_from_DE_memWrite
add wave -noupdate /integeration/output_from_DE_SP
add wave -noupdate /integeration/output_from_DE_Branch
add wave -noupdate /integeration/output_from_DE_Imm
add wave -noupdate /integeration/output_from_DE_PortFlag
add wave -noupdate /integeration/output_from_DE_In_port
add wave -noupdate /integeration/output_from_DE_SelectionLines
add wave -noupdate /integeration/output_from_DE_No_cond_jum
add wave -noupdate /integeration/output_from_DE_Data1
add wave -noupdate /integeration/output_from_DE_Data2
add wave -noupdate /integeration/output_from_DE_ImmediateValue
add wave -noupdate /integeration/output_from_DE_RS1
add wave -noupdate /integeration/output_from_DE_RS2
add wave -noupdate /integeration/output_from_DE_Rdst
add wave -noupdate /integeration/output_from_DE_M1
add wave -noupdate /integeration/output_from_EM_for_call
add wave -noupdate /integeration/output_from_EM_RTI
add wave -noupdate /integeration/output_from_EM_RET
add wave -noupdate /integeration/output_from_EM_PUSH
add wave -noupdate /integeration/output_from_EM_POP
add wave -noupdate /integeration/output_from_EM_Call
add wave -noupdate /integeration/output_from_EM_INT
add wave -noupdate /integeration/output_from_EM_WB_MemtoReg
add wave -noupdate /integeration/output_from_EM_WB_RegtoReg
add wave -noupdate /integeration/output_from_EM_portFlag
add wave -noupdate /integeration/output_from_EM_memRead
add wave -noupdate /integeration/output_from_EM_memWrite
add wave -noupdate /integeration/output_from_EM_SP
add wave -noupdate /integeration/output_from_EM_Inport
add wave -noupdate /integeration/output_from_EM_data_out
add wave -noupdate /integeration/output_from_EM_data1
add wave -noupdate /integeration/output_from_EM_Rdst
add wave -noupdate /integeration/output_from_EM_M1
add wave -noupdate /integeration/output_from_MM_RTI
add wave -noupdate /integeration/output_from_MM_call
add wave -noupdate /integeration/output_from_MM_RET
add wave -noupdate /integeration/output_from_MM_INT
add wave -noupdate /integeration/output_from_MM_WB_MemtoReg
add wave -noupdate /integeration/output_from_MM_WB_RegtoReg
add wave -noupdate /integeration/output_from_MM_memRead
add wave -noupdate /integeration/output_from_MM_memWrite
add wave -noupdate /integeration/output_from_MM_portFlag
add wave -noupdate /integeration/output_from_MM_data32
add wave -noupdate /integeration/output_from_MM_data_out
add wave -noupdate /integeration/output_from_MM_Rdst
add wave -noupdate /integeration/output_from_MM_M1
add wave -noupdate /integeration/output_from_MM_InPort
add wave -noupdate /integeration/Output_from_MWB_RTI
add wave -noupdate /integeration/Output_from_MWB_Ret
add wave -noupdate /integeration/Output_from_MWB_call
add wave -noupdate /integeration/Output_from_MWB_WBregToreg
add wave -noupdate /integeration/Output_from_MWB_memToreg
add wave -noupdate /integeration/Output_from_MWB_Int
add wave -noupdate /integeration/Output_from_MWB_Portflag
add wave -noupdate /integeration/Output_from_MWB_data_out
add wave -noupdate /integeration/Output_from_MWB_ReadDataAfter32
add wave -noupdate /integeration/Output_from_MWB_Inport
add wave -noupdate /integeration/Output_from_MWB_M1
add wave -noupdate /integeration/Output_from_MWB_Rdst
add wave -noupdate /integeration/Output_from_F_For_call
add wave -noupdate /integeration/Output_from_F_Instruction
add wave -noupdate /integeration/Output_from_F_PC_For_int
add wave -noupdate /integeration/Output_from_D_memRead
add wave -noupdate /integeration/Output_from_D_memWrite
add wave -noupdate /integeration/Output_from_E_PCsource
add wave -noupdate /integeration/Output_from_E_dataOut
add wave -noupdate /integeration/Output_from_E_CCR
add wave -noupdate /integeration/Output_from_M_readData
add wave -noupdate /integeration/Output_from_WB_WBvalue
add wave -noupdate /integeration/Output_from_WB_CCR
add wave -noupdate /integeration/freeze_pc_hdu
add wave -noupdate /integeration/stopCu_hdu
add wave -noupdate /integeration/freeze_pc_hsu
add wave -noupdate /integeration/stopCu_hsu
add wave -noupdate /integeration/Or_big
add wave -noupdate /integeration/flushSignal
add wave -noupdate /integeration/stopCU
add wave -noupdate /integeration/FDbufferstall
add wave -noupdate /integeration/Or_bigreset
TreeUpdate [SetDefaultTree]
WaveRestoreCursors {{Cursor 1} {480 ps} 0}
quietly wave cursor active 1
configure wave -namecolwidth 277
configure wave -valuecolwidth 100
configure wave -justifyvalue left
configure wave -signalnamewidth 0
configure wave -snapdistance 10
configure wave -datasetprefix 0
configure wave -rowmargin 4
configure wave -childrowmargin 2
configure wave -gridoffset 0
configure wave -gridperiod 1
configure wave -griddelta 40
configure wave -timeline 0
configure wave -timelineunits ps
update
WaveRestoreZoom {0 ps} {727 ps}
